name: Echo on push

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master
    types:
        - closed
        - opened

  workflow_dispatch:

jobs:
  echo-main-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Echo Hello
        run: echo "Hello, world!"

  echo-master-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Echo master branch
        run: echo "Hello, master branch!"

  echo-pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Echo Pull Request
        run: echo "This is a pull request event!"
        
  echo-pull-request-opened:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Echo Pull Request Opened
        run: echo "This is a pull request opened event executed!"

  echo-pull-request-closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Echo Pull Request
        run: echo "This is a pull request event!"      
  
  echo-workflow-dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
        - name: Echo workflow_dispatch
          run: echo "This is a workflow_dispatch event!"